import React from "react";
import {createRoot} from "react-dom/client";
import {Github,Linkedin,Mail,ArrowUpRight,Download} from "lucide-react";
import "./index.css";

function App(){return <div className="site">
<header className="nav"><a className="logo" href="#home">RS<span>.</span></a><nav><a href="#about">About</a><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#skills">Skills</a><a href="#contact">Contact</a></nav><a className="nav-mail" href="mailto:shahritij2004@gmail.com">Email me</a></header>
<main>
<section id="home" className="hero"><div><p className="label">HELLO, I'M RITIJ</p><h1>Computer Science<br/><em>graduate.</em></h1><p className="intro">I like building things with Python, SQL and JavaScript. I've worked on web applications, data projects and machine learning.</p><div className="buttons"><a className="button dark" href="#projects">See my work <ArrowUpRight size={16}/></a><a className="button" href="#contact"><Download size={15}/> Contact me</a></div><div className="socials"><a href="https://github.com/RitijS16?tab=repositories" target="_blank" rel="noreferrer"><Github size={17}/>GitHub</a><a href="https://www.linkedin.com/in/ritij-shah" target="_blank" rel="noreferrer"><Linkedin size={17}/>LinkedIn</a><a href="mailto:shahritij2004@gmail.com"><Mail size={17}/>Email</a></div></div><div className="hero-note"><p>currently looking for<br/><strong>an opportunity to learn<br/>and build.</strong></p><div className="code"><div>ritij.py <span>● ● ●</span></div><pre>{`name = "Ritij"
degree = "B.Tech CSE"
tools = ["Python", "SQL", "React"]
status = "open to work"`}</pre></div></div></section>

<section id="about" className="section"><small>01</small><div><p className="label">ABOUT</p><h2>Not trying to know everything.<br/>Just trying to get better.</h2><div className="cols"><p>I'm a Computer Science graduate from Bharati Vidyapeeth. My work so far has moved between software development, data analysis and Python/ML.</p><p>Outside code, I've worked in esports event operations and stakeholder coordination. I enjoy practical problems where I can build or improve something.</p></div></div></section>

<section id="experience" className="section"><small>02</small><div><p className="label">EXPERIENCE</p><h2>Where I've worked.</h2><article className="row"><time>JAN 2026 — JUN 2026</time><div><h3>Full Stack Intern <i>@ Terabit Support</i></h3><p>Worked on full-stack web development using React.js and Django, including REST APIs, validation, asynchronous operations and frontend/backend integration.</p></div></article><article className="row"><time>JUN 2025 — AUG 2025</time><div><h3>Python Intern <i>@ PHD Project</i></h3><p>Worked on cancer-detection ML research covering preprocessing, feature engineering, predictive modelling, SHAP explainability and model evaluation.</p></div></article><article className="row"><time>MAR 2025 — JUN 2026</time><div><h3>Operations Executive <i>@ Aftermath Ventures</i></h3><p>Handled esports and technology event operations, including logistics, scheduling, resource allocation and stakeholder coordination.</p></div></article></div></section>

<section id="projects" className="section"><small>03</small><div><p className="label">PROJECTS</p><h2>A few things I've built.</h2><article className="project"><b>01</b><div><label>PYTHON · MACHINE LEARNING</label><h3>Personal Finance & EMI Advisor</h3><p>Built a finance platform for expense tracking, EMI analysis, debt management, financial health scoring and recommendations. Used Random Forest and Isolation Forest on 10K+ synthetic profiles.</p><div className="tags">Python · Pandas · Scikit-learn · OpenAI</div></div><a href="https://github.com/RitijS16?tab=repositories" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a></article><article className="project"><b>02</b><div><label>DATA ANALYSIS</label><h3>Uber Data Analysis</h3><p>Analyzed 100K+ trip records to find peak-hour demand, trip-duration patterns and high-demand locations, then turned the findings into visual reports.</p><div className="tags">Python · SQL · Pandas · Power BI</div></div><a href="https://github.com/RitijS16?tab=repositories" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a></article><article className="project"><b>03</b><div><label>CYBERSECURITY · MACHINE LEARNING</label><h3>AI Network Intrusion Detection System</h3><p>Built a machine-learning based network intrusion detection demo using Random Forest and Isolation Forest to classify suspicious network traffic and flag anomalies.</p><div className="tags">Python · Scikit-learn · Random Forest · Isolation Forest</div></div><a href="https://github.com/RitijS16?tab=repositories" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a></article></div></section>

<section id="skills" className="section"><small>04</small><div><p className="label">SKILLS</p><h2>What I use.</h2><div className="skill-grid"><div><h3>Data</h3><p>Python · Pandas · NumPy · SQL · Power BI · Tableau · Excel · Matplotlib · Scikit-learn</p></div><div><h3>Development</h3><p>React.js · Django · JavaScript · HTML · CSS · REST APIs</p></div><div><h3>Databases & Cloud</h3><p>MySQL · PostgreSQL · MongoDB · AWS · Linux</p></div></div></div></section>

<section className="section"><small>05</small><div><p className="label">EDUCATION</p><h2>Education.</h2><div className="edu"><div><h3>B.Tech — Computer Science & Engineering</h3><p>Bharati Vidyapeeth (Deemed to be University), Pune</p></div><strong>8.2 CGPA · 2026</strong></div><div className="edu"><div><h3>HSC — Science</h3><p>PK Patil Junior College of Science</p></div><strong>81% · 2022</strong></div></div></section>

<section id="contact" className="contact"><p className="label">06 · CONTACT</p><h2>Have something<br/><em>interesting?</em></h2><p>I'm open to entry-level opportunities in development, data and related roles.</p><a href="mailto:shahritij2004@gmail.com">shahritij2004@gmail.com <ArrowUpRight size={18}/></a></section>
</main><footer><span>RITIJ SHAH</span><span>MUMBAI, INDIA · 2026</span></footer></div>}
createRoot(document.getElementById("root")).render(<App/>);